export const EVENTS = {
	JOIN: 'JOIN',
	ADD_VIEWER_PEER: 'ADD_VIEWER_PEER',
	REMOVE_PEER: 'REMOVE_PEER',
	RELAY_ICE: 'RELAY_ICE',
	RELAY_SDP: 'RELAY_SDP',
	SHARE_CAMERA_PEER_ID: 'SHARE_CAMERA_PEER_ID',
	LEAVE: 'LEAVE',
	CAMERA_OFFLINE: 'CAMERA_OFFLINE',
	DELETE_VIEWER: 'DELETE_VIEWER',
} as const

export type EventType = (typeof EVENTS)[keyof typeof EVENTS]
